/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ParkingSlotDao;
import DAO.UserDao;
import DAO.VehicleDao;
import MODELS.User;
import VIEW.Main.ReportType;

/**
 *
 * @author Fabrice
 */
public class DashboardPage extends javax.swing.JPanel {

    private Main main;
    private ParkingSlotDao slotDao = new ParkingSlotDao();
    private VehicleDao vehicleDao = new VehicleDao();
    private UserDao userDao = new UserDao();
    /**
     * Creates new form DashboardPage2
     */
    public DashboardPage(Main main) {
        this.main = main;
        initComponents();
        updateLabels();
        User activeUser = main.getCurrentUser();
        
        if (activeUser != null && activeUser.getRole() != null) {
            if (!"admin".equalsIgnoreCase(activeUser.getRole())) {
                viewAllVehiclesPage.setVisible(false);
            } else {
                viewAllVehiclesPage.setVisible(true);
            }
        }
    }
    
    private void updateLabels() {
        int totalSlots = slotDao.countSlots();
        int availableSlots = slotDao.getAvailableSlots().size();
        int occupiedSlots = slotDao.getAllSlots().size() - slotDao.getAvailableSlots().size();
        totalSpotsLabel.setText(String.valueOf(totalSlots));
        availableSpotsLabel.setText(String.valueOf(availableSlots));
        occupiedSpotsLabel.setText(String.valueOf(occupiedSlots));
        try {
            vehicleEnteredTodayLabel.setText(String.valueOf(vehicleDao.getVehiclesEnteredTodayCount()));
            vehicleExitedTodayLabel.setText(String.valueOf(vehicleDao.getVehiclesExitedTodayCount()));
            double total = slotDao.getTodayTotalRevenue();
            todayRevenueLabel.setText(total + " RWF");
        } catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        availableSpotsLabel = new javax.swing.JLabel();
        availableSpotsBtn = new javax.swing.JButton();
        viewVehicleExitPage = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        occupiedSpotsLabel = new javax.swing.JLabel();
        occupiedSpotsBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        totalSpotsLabel = new javax.swing.JLabel();
        viewParkingSlots = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        vehicleExitedTodayLabel = new javax.swing.JLabel();
        vehicleExitedTodayBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        todayRevenueLabel = new javax.swing.JLabel();
        todayRevenueBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        vehicleEnteredTodayLabel = new javax.swing.JLabel();
        vehicleEnteredTodayBtn = new javax.swing.JButton();
        viewAllVehiclesPage = new javax.swing.JButton();
        viewVehicleEntryPage = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("PARKING MANAGEMENT SYSTEM");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jPanel2.setMinimumSize(new java.awt.Dimension(280, 190));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 117, 125));
        jLabel2.setText("Available Spots");

        availableSpotsLabel.setBackground(new java.awt.Color(255, 255, 255));
        availableSpotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        availableSpotsLabel.setForeground(new java.awt.Color(40, 167, 69));
        availableSpotsLabel.setText("34");
        availableSpotsLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        availableSpotsLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        availableSpotsLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        availableSpotsBtn.setBackground(new java.awt.Color(51, 102, 255));
        availableSpotsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        availableSpotsBtn.setForeground(new java.awt.Color(255, 255, 255));
        availableSpotsBtn.setText("View");
        availableSpotsBtn.setBorderPainted(false);
        availableSpotsBtn.setContentAreaFilled(false);
        availableSpotsBtn.setFocusPainted(false);
        availableSpotsBtn.setOpaque(true);
        availableSpotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableSpotsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(availableSpotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(availableSpotsBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(availableSpotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(availableSpotsBtn)
                .addContainerGap())
        );

        viewVehicleExitPage.setBackground(new java.awt.Color(51, 102, 255));
        viewVehicleExitPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewVehicleExitPage.setForeground(new java.awt.Color(255, 255, 255));
        viewVehicleExitPage.setText("Vehicle Exit");
        viewVehicleExitPage.setContentAreaFilled(false);
        viewVehicleExitPage.setFocusPainted(false);
        viewVehicleExitPage.setOpaque(true);
        viewVehicleExitPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVehicleExitPageActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 190));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 117, 125));
        jLabel4.setText("Occupied Spots");

        occupiedSpotsLabel.setBackground(new java.awt.Color(255, 255, 255));
        occupiedSpotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        occupiedSpotsLabel.setForeground(new java.awt.Color(255, 51, 51));
        occupiedSpotsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occupiedSpotsLabel.setText("34");
        occupiedSpotsLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        occupiedSpotsLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        occupiedSpotsLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        occupiedSpotsBtn.setBackground(new java.awt.Color(51, 102, 255));
        occupiedSpotsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        occupiedSpotsBtn.setForeground(new java.awt.Color(255, 255, 255));
        occupiedSpotsBtn.setText("View");
        occupiedSpotsBtn.setBorderPainted(false);
        occupiedSpotsBtn.setContentAreaFilled(false);
        occupiedSpotsBtn.setFocusPainted(false);
        occupiedSpotsBtn.setOpaque(true);
        occupiedSpotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupiedSpotsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(80, 80, 80))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(occupiedSpotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(occupiedSpotsBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(occupiedSpotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(occupiedSpotsBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jPanel4.setMinimumSize(new java.awt.Dimension(280, 190));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 117, 125));
        jLabel6.setText("Total Spots");

        totalSpotsLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalSpotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        totalSpotsLabel.setForeground(new java.awt.Color(33, 37, 41));
        totalSpotsLabel.setText("34");
        totalSpotsLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        totalSpotsLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        viewParkingSlots.setBackground(new java.awt.Color(51, 102, 255));
        viewParkingSlots.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewParkingSlots.setForeground(new java.awt.Color(255, 255, 255));
        viewParkingSlots.setText("View");
        viewParkingSlots.setBorderPainted(false);
        viewParkingSlots.setContentAreaFilled(false);
        viewParkingSlots.setFocusPainted(false);
        viewParkingSlots.setOpaque(true);
        viewParkingSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewParkingSlotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(totalSpotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(viewParkingSlots)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addComponent(totalSpotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(viewParkingSlots)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jPanel5.setMinimumSize(new java.awt.Dimension(280, 190));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 117, 125));
        jLabel8.setText("Vehicle Exited Today");

        vehicleExitedTodayLabel.setBackground(new java.awt.Color(255, 255, 255));
        vehicleExitedTodayLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        vehicleExitedTodayLabel.setForeground(new java.awt.Color(33, 37, 41));
        vehicleExitedTodayLabel.setText("34");
        vehicleExitedTodayLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        vehicleExitedTodayLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        vehicleExitedTodayLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        vehicleExitedTodayBtn.setBackground(new java.awt.Color(51, 102, 255));
        vehicleExitedTodayBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehicleExitedTodayBtn.setForeground(new java.awt.Color(255, 255, 255));
        vehicleExitedTodayBtn.setText("View");
        vehicleExitedTodayBtn.setBorderPainted(false);
        vehicleExitedTodayBtn.setContentAreaFilled(false);
        vehicleExitedTodayBtn.setFocusPainted(false);
        vehicleExitedTodayBtn.setOpaque(true);
        vehicleExitedTodayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleExitedTodayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(vehicleExitedTodayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(vehicleExitedTodayBtn)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(45, 45, 45)
                .addComponent(vehicleExitedTodayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(vehicleExitedTodayBtn)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jPanel6.setMinimumSize(new java.awt.Dimension(280, 190));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(108, 117, 125));
        jLabel10.setText("Today's Revenue");

        todayRevenueLabel.setBackground(new java.awt.Color(255, 255, 255));
        todayRevenueLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        todayRevenueLabel.setForeground(new java.awt.Color(33, 37, 41));
        todayRevenueLabel.setText("34");
        todayRevenueLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        todayRevenueLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        todayRevenueLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        todayRevenueBtn.setBackground(new java.awt.Color(51, 102, 255));
        todayRevenueBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        todayRevenueBtn.setForeground(new java.awt.Color(255, 255, 255));
        todayRevenueBtn.setText("View");
        todayRevenueBtn.setBorderPainted(false);
        todayRevenueBtn.setContentAreaFilled(false);
        todayRevenueBtn.setFocusPainted(false);
        todayRevenueBtn.setOpaque(true);
        todayRevenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayRevenueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(todayRevenueBtn)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(todayRevenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(todayRevenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(todayRevenueBtn)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jPanel7.setMinimumSize(new java.awt.Dimension(280, 190));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(108, 117, 125));
        jLabel12.setText("Vehicle Entered Today");

        vehicleEnteredTodayLabel.setBackground(new java.awt.Color(255, 255, 255));
        vehicleEnteredTodayLabel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        vehicleEnteredTodayLabel.setForeground(new java.awt.Color(33, 37, 41));
        vehicleEnteredTodayLabel.setText("34");
        vehicleEnteredTodayLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        vehicleEnteredTodayLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        vehicleEnteredTodayLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        vehicleEnteredTodayBtn.setBackground(new java.awt.Color(51, 102, 255));
        vehicleEnteredTodayBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehicleEnteredTodayBtn.setForeground(new java.awt.Color(255, 255, 255));
        vehicleEnteredTodayBtn.setText("View");
        vehicleEnteredTodayBtn.setBorderPainted(false);
        vehicleEnteredTodayBtn.setContentAreaFilled(false);
        vehicleEnteredTodayBtn.setFocusPainted(false);
        vehicleEnteredTodayBtn.setOpaque(true);
        vehicleEnteredTodayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleEnteredTodayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(vehicleEnteredTodayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel12))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(vehicleEnteredTodayBtn)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(49, 49, 49)
                .addComponent(vehicleEnteredTodayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(vehicleEnteredTodayBtn)
                .addContainerGap())
        );

        viewAllVehiclesPage.setBackground(new java.awt.Color(51, 102, 255));
        viewAllVehiclesPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAllVehiclesPage.setForeground(new java.awt.Color(255, 255, 255));
        viewAllVehiclesPage.setText("View All Vehicles");
        viewAllVehiclesPage.setContentAreaFilled(false);
        viewAllVehiclesPage.setFocusPainted(false);
        viewAllVehiclesPage.setOpaque(true);
        viewAllVehiclesPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllVehiclesPageActionPerformed(evt);
            }
        });

        viewVehicleEntryPage.setBackground(new java.awt.Color(51, 102, 255));
        viewVehicleEntryPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewVehicleEntryPage.setForeground(new java.awt.Color(255, 255, 255));
        viewVehicleEntryPage.setText("Vehicle Entry");
        viewVehicleEntryPage.setContentAreaFilled(false);
        viewVehicleEntryPage.setFocusPainted(false);
        viewVehicleEntryPage.setOpaque(true);
        viewVehicleEntryPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVehicleEntryPageActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140)
                .addComponent(logoutBtn)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(viewVehicleEntryPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewVehicleExitPage)
                .addGap(240, 240, 240)
                .addComponent(viewAllVehiclesPage)
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logoutBtn))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAllVehiclesPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewVehicleExitPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewVehicleEntryPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewVehicleExitPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVehicleExitPageActionPerformed
        // TODO add your handling code here:
        main.setPage(new VehicleExitPage(main));
    }//GEN-LAST:event_viewVehicleExitPageActionPerformed

    private void viewAllVehiclesPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllVehiclesPageActionPerformed
        // TODO add your handling code here:
        main.setPage(new VehicleOverViewPage(main));
    }//GEN-LAST:event_viewAllVehiclesPageActionPerformed

    private void viewVehicleEntryPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVehicleEntryPageActionPerformed
        // TODO add your handling code here:
        main.setPage(new VehicleEntryPage(main));
    }//GEN-LAST:event_viewVehicleEntryPageActionPerformed

    private void viewParkingSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewParkingSlotsActionPerformed
        // TODO add your handling code here:
        main.setPage(new SlotsPage(main));
    }//GEN-LAST:event_viewParkingSlotsActionPerformed

    private void availableSpotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableSpotsBtnActionPerformed
        // TODO add your handling code here:
        main.showReportPage(ReportType.AVAILABLE_SPOTS);
    }//GEN-LAST:event_availableSpotsBtnActionPerformed

    private void occupiedSpotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupiedSpotsBtnActionPerformed
        // TODO add your handling code here:
        main.showReportPage(ReportType.OCCUPIED_SPOTS);
    }//GEN-LAST:event_occupiedSpotsBtnActionPerformed

    private void vehicleEnteredTodayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleEnteredTodayBtnActionPerformed
        // TODO add your handling code here:
        main.showReportPage(ReportType.VEHICLES_ENTERED_TODAY);
    }//GEN-LAST:event_vehicleEnteredTodayBtnActionPerformed

    private void vehicleExitedTodayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleExitedTodayBtnActionPerformed
        // TODO add your handling code here:
        main.showReportPage(ReportType.VEHICLES_EXITED_TODAY);
    }//GEN-LAST:event_vehicleExitedTodayBtnActionPerformed

    private void todayRevenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayRevenueBtnActionPerformed
        // TODO add your handling code here:
        main.showReportPage(ReportType.TODAY_REVENUE);
    }//GEN-LAST:event_todayRevenueBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to log out?", 
            "Confirm Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (dialogResult == javax.swing.JOptionPane.YES_OPTION) {
            userDao.logoutUser(main);
            main.setPage(new LoginUserPage(main));
        }
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availableSpotsBtn;
    private javax.swing.JLabel availableSpotsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton occupiedSpotsBtn;
    private javax.swing.JLabel occupiedSpotsLabel;
    private javax.swing.JButton todayRevenueBtn;
    private javax.swing.JLabel todayRevenueLabel;
    private javax.swing.JLabel totalSpotsLabel;
    private javax.swing.JButton vehicleEnteredTodayBtn;
    private javax.swing.JLabel vehicleEnteredTodayLabel;
    private javax.swing.JButton vehicleExitedTodayBtn;
    private javax.swing.JLabel vehicleExitedTodayLabel;
    private javax.swing.JButton viewAllVehiclesPage;
    private javax.swing.JButton viewParkingSlots;
    private javax.swing.JButton viewVehicleEntryPage;
    private javax.swing.JButton viewVehicleExitPage;
    // End of variables declaration//GEN-END:variables
}
