/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ParkingSlotDao;
import DAO.ResultSetToTableModelConverter;
import DAO.VehicleDao;
import VIEW.Main.ReportType;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Fabrice
 */
public class ReportTablePage extends javax.swing.JPanel {
    
    

    private Main main;
    private ReportType reportType;
    private ParkingSlotDao slotDao = new ParkingSlotDao();
    private VehicleDao vehicleDao = new VehicleDao();
    /**
     * Creates new form ReportTablePage
     */
    public ReportTablePage(Main main, ReportType reportType) {
        this.main = main;
        this.reportType = reportType;
        
        initMyPage();
    }
    
    private void initMyPage() {
        initComponents();
        loadTableData();
    }

    
    private void loadTableData() {
    try {
        switch (reportType) {
            case AVAILABLE_SPOTS:
                ResultSet rsAvailable = slotDao.getAvailableSlotsRs();
                table.setModel(ResultSetToTableModelConverter.resultSetToTableModel(rsAvailable));
                break;

            case OCCUPIED_SPOTS:
                ResultSet rsOccupied = slotDao.getOccupiedSlots();
                table.setModel(ResultSetToTableModelConverter.resultSetToTableModel(rsOccupied));
                break;

            case VEHICLES_ENTERED_TODAY:
                ResultSet rsEntered = vehicleDao.getVehiclesEnteredToday();
                table.setModel(ResultSetToTableModelConverter.resultSetToTableModel(rsEntered));
                break;

            case VEHICLES_EXITED_TODAY:
                ResultSet rsExited = vehicleDao.getVehiclesExitedToday();
                table.setModel(ResultSetToTableModelConverter.resultSetToTableModel(rsExited));
                break;

            case TODAY_REVENUE:
                ResultSet rsRevenue = slotDao.getTodayRevenueDetails();
                table.setModel(ResultSetToTableModelConverter.resultSetToTableModel(rsRevenue));

                double total = slotDao.getTodayTotalRevenue();
                revenueLabel.setText("TOTAL : " + total + " RWF");
                break;
        }
    } catch (SQLException e) {
        e.printStackTrace(); 
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backToDashboardBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        revenueLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));

        backToDashboardBtn.setBackground(new java.awt.Color(255, 255, 255));
        backToDashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/circle-arrow-left (1).png"))); // NOI18N
        backToDashboardBtn.setBorderPainted(false);
        backToDashboardBtn.setContentAreaFilled(false);
        backToDashboardBtn.setFocusPainted(false);
        backToDashboardBtn.setOpaque(true);
        backToDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        revenueLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(backToDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 740, Short.MAX_VALUE)
                        .addComponent(revenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(backToDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(revenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardBtnActionPerformed
        // TODO add your handling code here:
        main.setPage(new DashboardPage(main));
    }//GEN-LAST:event_backToDashboardBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel revenueLabel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
