/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ParkingSlotDao;
import MODELS.ParkingSlot;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Fabrice
 */
public class SlotsPage extends javax.swing.JPanel {

    private Main main;
    private ParkingSlotDao slotDao = new ParkingSlotDao();
    /**
     * Creates new form SlotsPage
     */
    public SlotsPage(Main main) {
        this.main = main;
        initComponents();
        updateSlotsLabel();
    }
    
    private void updateSlotsLabel() {
        try {
            int total = slotDao.countSlots();
            slotsTotalNumberLabel.setText(String.valueOf(total));
            
            int carCount = slotDao.countSlotsByType("Car");
            int motorcycleCount = slotDao.countSlotsByType("Motorcycle");
            int truckCount = slotDao.countSlotsByType("Truck");
            int busCount = slotDao.countSlotsByType("Bus");

            totalCarSlotsLabel.setText(String.valueOf(carCount));
            totalMotorcycleSlotsLabel.setText(String.valueOf(motorcycleCount));
            totalTruckSlotsLabel.setText(String.valueOf(truckCount));
            totalBusSlotsLabel.setText(String.valueOf(busCount));
            
        } catch (Exception ex) {
            System.err.println("Error updating slot labels: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Failed to load slot data.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        slotNumberField = new javax.swing.JTextField();
        addNewSlotsBtn = new javax.swing.JButton();
        removeSlotsBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        slotTypeComboBox = new javax.swing.JComboBox<>();
        backToDashboardBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        slotsTotalNumberLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalCarSlotsLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalMotorcycleSlotsLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalTruckSlotsLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalBusSlotsLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Slots Page");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Number of slots:");

        slotNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        addNewSlotsBtn.setBackground(new java.awt.Color(51, 102, 255));
        addNewSlotsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addNewSlotsBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNewSlotsBtn.setText("Add");
        addNewSlotsBtn.setBorderPainted(false);
        addNewSlotsBtn.setContentAreaFilled(false);
        addNewSlotsBtn.setFocusPainted(false);
        addNewSlotsBtn.setMinimumSize(new java.awt.Dimension(40, 25));
        addNewSlotsBtn.setOpaque(true);
        addNewSlotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewSlotsBtnActionPerformed(evt);
            }
        });

        removeSlotsBtn.setBackground(new java.awt.Color(255, 51, 51));
        removeSlotsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeSlotsBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeSlotsBtn.setText("Remove");
        removeSlotsBtn.setBorderPainted(false);
        removeSlotsBtn.setContentAreaFilled(false);
        removeSlotsBtn.setFocusPainted(false);
        removeSlotsBtn.setOpaque(true);
        removeSlotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSlotsBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Slot Type");

        slotTypeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        slotTypeComboBox.setForeground(new java.awt.Color(33, 37, 41));
        slotTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motorcycle", "Truck", "Bus" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(addNewSlotsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(removeSlotsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slotTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slotNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(slotNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(slotTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewSlotsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeSlotsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        backToDashboardBtn.setBackground(new java.awt.Color(255, 255, 255));
        backToDashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/circle-arrow-left (1).png"))); // NOI18N
        backToDashboardBtn.setBorderPainted(false);
        backToDashboardBtn.setContentAreaFilled(false);
        backToDashboardBtn.setFocusPainted(false);
        backToDashboardBtn.setOpaque(true);
        backToDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Total number of slots:");

        slotsTotalNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotsTotalNumberLabel.setText("34");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Total Car slots:");

        totalCarSlotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalCarSlotsLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalCarSlotsLabel.setText("34");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Total Motorcycle slots:");

        totalMotorcycleSlotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalMotorcycleSlotsLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalMotorcycleSlotsLabel.setText("34");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Total Truck slots:");

        totalTruckSlotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalTruckSlotsLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalTruckSlotsLabel.setText("34");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Total Bus slots:");

        totalBusSlotsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalBusSlotsLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalBusSlotsLabel.setText("34");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slotsTotalNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalBusSlotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalTruckSlotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalCarSlotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(totalMotorcycleSlotsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(237, 237, 237))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalCarSlotsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalMotorcycleSlotsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalTruckSlotsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalBusSlotsLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(slotsTotalNumberLabel))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(backToDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(backToDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewSlotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewSlotsBtnActionPerformed
        // TODO add your handling code here:
        try {
            int number = Integer.parseInt(slotNumberField.getText().trim());
            if (number <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Enter a positive number");
                return;
            }
            
            String lastSlot = "0";
            if (slotDao.countSlots() != 0){
                lastSlot = slotDao.getLastSlot().getSlotNumber();
            }

            for (int i = 1; i <= number; i++) {
                ParkingSlot slot = new ParkingSlot();

                int newNumber = Integer.parseInt(lastSlot) + i;
                slot.setSlotNumber(String.valueOf(newNumber));
                slot.setSlotType((String)slotTypeComboBox.getSelectedItem());
                slot.setIsOccupied(false);

                slotDao.createSlot(slot);
            }

            javax.swing.JOptionPane.showMessageDialog(this, number + " slots added successfully");

            updateSlotsLabel();
            slotNumberField.setText("");

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number entered");
        }
    }//GEN-LAST:event_addNewSlotsBtnActionPerformed

    private void backToDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardBtnActionPerformed
        // TODO add your handling code here:
        main.setPage(new DashboardPage(main));
    }//GEN-LAST:event_backToDashboardBtnActionPerformed

    private void removeSlotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSlotsBtnActionPerformed
        // TODO add your handling code here:
        String slotType = (String) slotTypeComboBox.getSelectedItem();
        String numberText = slotNumberField.getText().trim();

        if (numberText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter the number of slots to remove");
            return;
        }

        try {
            int numberToRemove = Integer.parseInt(numberText);

            if (numberToRemove <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Enter a positive number");
                return;
            }

            List<ParkingSlot> slotsToRemove = slotDao.findRemovableSlotsByType(slotType, numberToRemove);

            int successfullyRemoved = 0;

            if (slotsToRemove.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No unoccupied " + slotType + " slots are available to remove");
                return;
            }

            for (ParkingSlot slot : slotsToRemove) {
                if (!slot.isIsOccupied()) {
                    slotDao.deleteSlot(slot.getSlotId());
                    successfullyRemoved++;
                }
            }

            if (successfullyRemoved > 0) {
                String message = successfullyRemoved + " unoccupied " + slotType + " slots removed successfully";

                if (successfullyRemoved < numberToRemove) {
                     message += "\n(Only " + successfullyRemoved + " slots were available for removal)";
                }
                javax.swing.JOptionPane.showMessageDialog(this, message);
            } else {
                 javax.swing.JOptionPane.showMessageDialog(this, "No slots were removed");
            }

            updateSlotsLabel();
            slotNumberField.setText("");

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number entered");
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred during slot removal", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeSlotsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewSlotsBtn;
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton removeSlotsBtn;
    private javax.swing.JTextField slotNumberField;
    private javax.swing.JComboBox<String> slotTypeComboBox;
    private javax.swing.JLabel slotsTotalNumberLabel;
    private javax.swing.JLabel totalBusSlotsLabel;
    private javax.swing.JLabel totalCarSlotsLabel;
    private javax.swing.JLabel totalMotorcycleSlotsLabel;
    private javax.swing.JLabel totalTruckSlotsLabel;
    // End of variables declaration//GEN-END:variables
}
